title: Rachel Wang
description: Welcome to My Personal Blog
author: Rachel Wang
logo: /RachelWang.github.io/static/img/avatar.png
github: https://github.com/Rachel7
about: Programmer

baseurl: "https://racheal7.github.io/RachelWang.github.io/"
url: "https://racheal7.github.io/RachelWang.github.io/"

allowsearch: true

disqus_shortname: ruiqiwang
google_analytics: UA-72862926-1

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
